-- Giveaway ticket balance v2:
-- purchases accumulate in a spendable balance and participants choose how much to use.

alter table public.giveaway_ticket_balances
    add column if not exists available_tickets integer not null default 0;

update public.giveaway_ticket_balances b
set available_tickets = greatest(
    b.tickets - coalesce(
        (
            select greatest(1, coalesce(p.tickets_used, 1))
            from public.participants p
            where p.giveaway_id = b.giveaway_id
              and p.user_id = b.user_id
            limit 1
        ),
        1
    ),
    0
);

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'giveaway_ticket_balances_available_nonnegative'
          and conrelid = 'public.giveaway_ticket_balances'::regclass
    ) then
        alter table public.giveaway_ticket_balances
            add constraint giveaway_ticket_balances_available_nonnegative
            check (available_tickets >= 0);
    end if;
end
$$;

create table if not exists public.giveaway_ticket_spends (
    id bigint generated by default as identity primary key,
    giveaway_id bigint not null references public.giveaways(id) on delete cascade,
    user_id bigint not null references public.users(telegram_id) on delete cascade,
    amount integer not null check (amount > 0),
    idempotency_key text not null unique,
    created_at timestamptz not null default now()
);

create index if not exists idx_giveaway_ticket_spends_user_giveaway
    on public.giveaway_ticket_spends (user_id, giveaway_id, created_at desc);

revoke all on public.giveaway_ticket_spends from anon, authenticated;
grant all on public.giveaway_ticket_spends to service_role;


create or replace function public.purchase_giveaway_tickets(
    p_user_id bigint,
    p_giveaway_id bigint,
    p_offer_code text,
    p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
    v_status text;
    v_offer public.ticket_offers%rowtype;
    v_points public.points%rowtype;
    v_existing public.points_transactions%rowtype;
    v_current integer;
    v_available integer;
    v_legacy integer;
    v_add integer;
    v_cost integer;
    v_new integer;
    v_new_available integer;
    v_new_balance integer;
begin
    perform pg_advisory_xact_lock(hashtextextended(p_idempotency_key, 0));

    select * into v_existing
    from public.points_transactions
    where idempotency_key = p_idempotency_key;

    if found then
        select coalesce(available_tickets, 0)
        into v_available
        from public.giveaway_ticket_balances
        where giveaway_id = p_giveaway_id and user_id = p_user_id;

        return jsonb_build_object(
            'ok', true,
            'duplicate', true,
            'tickets', coalesce((v_existing.metadata->>'tickets')::integer, 1),
            'available_tickets', coalesce(
                (v_existing.metadata->>'available_tickets')::integer,
                v_available,
                0
            ),
            'added', coalesce((v_existing.metadata->>'added')::integer, 0),
            'cost', abs(v_existing.amount),
            'new_balance', coalesce((v_existing.metadata->>'new_balance')::integer, 0)
        );
    end if;

    select status into v_status
    from public.giveaways
    where id = p_giveaway_id
    for share;

    if not found then
        return jsonb_build_object('ok', false, 'error', 'GIVEAWAY_NOT_FOUND');
    end if;
    if v_status <> 'active' then
        return jsonb_build_object('ok', false, 'error', 'GIVEAWAY_NOT_ACTIVE');
    end if;

    select * into v_offer
    from public.ticket_offers
    where code = p_offer_code and active = true;

    if not found then
        return jsonb_build_object('ok', false, 'error', 'OFFER_NOT_FOUND');
    end if;

    select coalesce(active_tickets, 0)
    into v_legacy
    from public.users
    where telegram_id = p_user_id
    for update;

    if not found then
        return jsonb_build_object('ok', false, 'error', 'USER_NOT_FOUND');
    end if;

    insert into public.giveaway_ticket_balances (
        giveaway_id,
        user_id,
        tickets,
        available_tickets
    )
    values (
        p_giveaway_id,
        p_user_id,
        greatest(1, v_legacy),
        greatest(0, v_legacy - 1)
    )
    on conflict (giveaway_id, user_id) do nothing;

    select tickets, available_tickets
    into v_current, v_available
    from public.giveaway_ticket_balances
    where giveaway_id = p_giveaway_id and user_id = p_user_id
    for update;

    v_add := v_offer.ticket_count;
    if v_add <= 0 then
        return jsonb_build_object('ok', false, 'error', 'INVALID_TICKET_AMOUNT');
    end if;

    v_cost := case
        when v_offer.pricing_mode = 'per_ticket' then v_offer.price_rp * v_add
        else v_offer.price_rp
    end;

    select * into v_points
    from public.points
    where user_id = p_user_id
    for update;

    if not found then
        return jsonb_build_object('ok', false, 'error', 'POINTS_NOT_FOUND');
    end if;

    if coalesce(v_points.total_points, 0) < v_cost then
        return jsonb_build_object('ok', false, 'error', 'INSUFFICIENT_POINTS');
    end if;

    v_new := v_current + v_add;
    v_new_available := v_available + v_add;
    v_new_balance := coalesce(v_points.total_points, 0) - v_cost;

    update public.giveaway_ticket_balances
    set tickets = v_new,
        available_tickets = v_new_available,
        purchased_rp = purchased_rp + v_cost,
        consumed_at = null,
        updated_at = now()
    where giveaway_id = p_giveaway_id and user_id = p_user_id;

    update public.users
    set active_tickets = 0
    where telegram_id = p_user_id;

    update public.points
    set spent_points = coalesce(spent_points, 0) + v_cost,
        total_points = v_new_balance,
        updated_at = now()
    where user_id = p_user_id;

    insert into public.points_transactions (
        user_id,
        amount,
        transaction_type,
        reference_type,
        reference_id,
        idempotency_key,
        metadata
    )
    values (
        p_user_id,
        -v_cost,
        'giveaway_ticket_purchase',
        'giveaway',
        p_giveaway_id,
        p_idempotency_key,
        jsonb_build_object(
            'offer_code', p_offer_code,
            'added', v_add,
            'tickets', v_new,
            'available_tickets', v_new_available,
            'new_balance', v_new_balance
        )
    );

    return jsonb_build_object(
        'ok', true,
        'tickets', v_new,
        'available_tickets', v_new_available,
        'added', v_add,
        'cost', v_cost,
        'new_balance', v_new_balance
    );
end;
$function$;


create or replace function public.join_giveaway_atomic(
    p_giveaway_id bigint,
    p_user_id bigint,
    p_username text
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
    v_status text;
    v_legacy integer;
    v_available integer;
    v_participant_id bigint;
begin
    select status into v_status
    from public.giveaways
    where id = p_giveaway_id
    for share;

    if not found then
        return jsonb_build_object('ok', false, 'error', 'GIVEAWAY_NOT_FOUND');
    end if;
    if v_status <> 'active' then
        return jsonb_build_object('ok', false, 'error', 'GIVEAWAY_NOT_ACTIVE');
    end if;

    select coalesce(active_tickets, 0)
    into v_legacy
    from public.users
    where telegram_id = p_user_id
    for update;

    if not found then
        return jsonb_build_object('ok', false, 'error', 'USER_NOT_FOUND');
    end if;

    insert into public.giveaway_ticket_balances (
        giveaway_id,
        user_id,
        tickets,
        available_tickets
    )
    values (
        p_giveaway_id,
        p_user_id,
        greatest(1, v_legacy),
        greatest(0, v_legacy - 1)
    )
    on conflict (giveaway_id, user_id) do nothing;

    select available_tickets
    into v_available
    from public.giveaway_ticket_balances
    where giveaway_id = p_giveaway_id and user_id = p_user_id
    for update;

    insert into public.participants (
        giveaway_id,
        user_id,
        username,
        tickets_used
    )
    values (
        p_giveaway_id,
        p_user_id,
        p_username,
        1
    )
    on conflict (giveaway_id, user_id) do nothing
    returning id into v_participant_id;

    if v_participant_id is null then
        return jsonb_build_object('ok', false, 'error', 'ALREADY_JOINED');
    end if;

    update public.giveaway_ticket_balances
    set consumed_at = null,
        updated_at = now()
    where giveaway_id = p_giveaway_id and user_id = p_user_id;

    update public.users
    set active_tickets = 0
    where telegram_id = p_user_id;

    return jsonb_build_object(
        'ok', true,
        'participant_id', v_participant_id,
        'tickets_used', 1,
        'available_tickets', coalesce(v_available, 0),
        'bonus_tickets_consumed', 0
    );
end;
$function$;


create or replace function public.spend_giveaway_tickets(
    p_user_id bigint,
    p_giveaway_id bigint,
    p_amount integer,
    p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
    v_status text;
    v_existing_amount integer;
    v_available integer;
    v_used integer;
    v_remaining integer;
begin
    if p_amount is null or p_amount <= 0 then
        return jsonb_build_object('ok', false, 'error', 'INVALID_TICKET_AMOUNT');
    end if;

    perform pg_advisory_xact_lock(
        hashtextextended('giveaway-ticket-spend:' || p_idempotency_key, 0)
    );

    select amount
    into v_existing_amount
    from public.giveaway_ticket_spends
    where idempotency_key = p_idempotency_key;

    if found then
        select coalesce(available_tickets, 0)
        into v_remaining
        from public.giveaway_ticket_balances
        where giveaway_id = p_giveaway_id and user_id = p_user_id;

        select greatest(1, coalesce(tickets_used, 1))
        into v_used
        from public.participants
        where giveaway_id = p_giveaway_id and user_id = p_user_id;

        return jsonb_build_object(
            'ok', true,
            'duplicate', true,
            'spent', v_existing_amount,
            'remaining', coalesce(v_remaining, 0),
            'tickets_used', coalesce(v_used, 1)
        );
    end if;

    select status
    into v_status
    from public.giveaways
    where id = p_giveaway_id
    for share;

    if not found then
        return jsonb_build_object('ok', false, 'error', 'GIVEAWAY_NOT_FOUND');
    end if;
    if v_status <> 'active' then
        return jsonb_build_object('ok', false, 'error', 'GIVEAWAY_NOT_ACTIVE');
    end if;

    select greatest(1, coalesce(tickets_used, 1))
    into v_used
    from public.participants
    where giveaway_id = p_giveaway_id and user_id = p_user_id
    for update;

    if not found then
        return jsonb_build_object('ok', false, 'error', 'NOT_PARTICIPATING');
    end if;

    select coalesce(available_tickets, 0)
    into v_available
    from public.giveaway_ticket_balances
    where giveaway_id = p_giveaway_id and user_id = p_user_id
    for update;

    if not found or v_available < p_amount then
        return jsonb_build_object('ok', false, 'error', 'INSUFFICIENT_TICKETS');
    end if;

    v_remaining := v_available - p_amount;
    v_used := v_used + p_amount;

    update public.giveaway_ticket_balances
    set available_tickets = v_remaining,
        updated_at = now()
    where giveaway_id = p_giveaway_id and user_id = p_user_id;

    update public.participants
    set tickets_used = v_used
    where giveaway_id = p_giveaway_id and user_id = p_user_id;

    insert into public.giveaway_ticket_spends (
        giveaway_id,
        user_id,
        amount,
        idempotency_key
    )
    values (
        p_giveaway_id,
        p_user_id,
        p_amount,
        p_idempotency_key
    );

    return jsonb_build_object(
        'ok', true,
        'spent', p_amount,
        'remaining', v_remaining,
        'tickets_used', v_used
    );
end;
$function$;


create or replace function public.consume_finished_giveaway_tickets()
returns trigger
language plpgsql
set search_path to 'public', 'pg_temp'
as $function$
begin
    if old.status = 'active' and new.status <> 'active' then
        update public.giveaway_ticket_balances
        set tickets = 1,
            available_tickets = 0,
            consumed_at = coalesce(consumed_at, now()),
            updated_at = now()
        where giveaway_id = new.id and consumed_at is null;
    end if;
    return new;
end;
$function$;

revoke all on function public.spend_giveaway_tickets(bigint, bigint, integer, text)
    from public, anon, authenticated;
grant execute on function public.spend_giveaway_tickets(bigint, bigint, integer, text)
    to service_role;

revoke all on function public.purchase_giveaway_tickets(bigint, bigint, text, text)
    from public, anon, authenticated;
grant execute on function public.purchase_giveaway_tickets(bigint, bigint, text, text)
    to service_role;

revoke all on function public.join_giveaway_atomic(bigint, bigint, text)
    from public, anon, authenticated;
grant execute on function public.join_giveaway_atomic(bigint, bigint, text)
    to service_role;
