begin;

create table if not exists public.store_lots (
    id bigint generated by default as identity primary key,
    title text not null check (length(trim(title)) between 1 and 120),
    description text not null default '',
    price_rp integer not null check (price_rp > 0),
    total_quantity integer not null check (total_quantity > 0),
    sold_quantity integer not null default 0 check (sold_quantity >= 0),
    image_url text,
    reward_type text not null default 'manual'
        check (reward_type in ('manual', 'ticket', 'role', 'channel', 'sticker', 'nft', 'physical', 'custom')),
    reward_payload jsonb not null default '{}'::jsonb,
    per_user_limit integer not null default 1 check (per_user_limit > 0),
    status text not null default 'draft'
        check (status in ('draft', 'active', 'sold_out', 'disabled', 'archived')),
    created_by bigint not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint store_lots_sold_not_above_total check (sold_quantity <= total_quantity)
);

create table if not exists public.store_purchases (
    id bigint generated by default as identity primary key,
    lot_id bigint not null references public.store_lots(id) on delete restrict,
    user_id bigint not null references public.users(telegram_id) on delete restrict,
    price_rp integer not null check (price_rp > 0),
    quantity integer not null default 1 check (quantity > 0),
    status text not null default 'paid'
        check (status in ('paid', 'fulfilled', 'cancelled', 'refunded')),
    idempotency_key text not null unique,
    fulfillment_note text,
    created_at timestamptz not null default now(),
    fulfilled_at timestamptz,
    fulfilled_by bigint
);

create table if not exists public.points_transactions (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(telegram_id) on delete cascade,
    amount integer not null check (amount <> 0),
    transaction_type text not null,
    reference_type text,
    reference_id bigint,
    idempotency_key text not null unique,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_store_lots_public
    on public.store_lots(status, created_at desc);
create index if not exists idx_store_purchases_lot
    on public.store_purchases(lot_id, created_at desc);
create index if not exists idx_store_purchases_user
    on public.store_purchases(user_id, created_at desc);
create index if not exists idx_store_purchases_fulfillment
    on public.store_purchases(status, created_at)
    where status = 'paid';
create index if not exists idx_points_transactions_user
    on public.points_transactions(user_id, created_at desc);

create or replace function public.store_touch_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_store_lots_updated_at on public.store_lots;
create trigger trg_store_lots_updated_at
before update on public.store_lots
for each row execute function public.store_touch_updated_at();

create or replace function public.purchase_store_tickets(
    p_user_id bigint,
    p_amount integer,
    p_unit_cost integer,
    p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_cost integer;
    v_points public.points%rowtype;
    v_existing public.points_transactions%rowtype;
    v_new_balance integer;
    v_new_tickets integer;
begin
    if p_amount not in (1, 5, 10) or p_unit_cost <> 50 then
        return jsonb_build_object('ok', false, 'error', 'INVALID_TICKET_OFFER');
    end if;

    select * into v_existing
    from public.points_transactions
    where idempotency_key = p_idempotency_key;

    if found then
        return jsonb_build_object(
            'ok', true,
            'duplicate', true,
            'new_balance', coalesce((v_existing.metadata->>'new_balance')::integer, 0),
            'tickets', coalesce((v_existing.metadata->>'tickets')::integer, 0)
        );
    end if;

    v_cost := p_amount * p_unit_cost;

    select * into v_points
    from public.points
    where user_id = p_user_id
    for update;

    if not found then
        return jsonb_build_object('ok', false, 'error', 'POINTS_NOT_FOUND');
    end if;

    if coalesce(v_points.total_points, 0) < v_cost then
        return jsonb_build_object('ok', false, 'error', 'INSUFFICIENT_POINTS');
    end if;

    update public.users
    set active_tickets = coalesce(active_tickets, 0) + p_amount
    where telegram_id = p_user_id
    returning active_tickets into v_new_tickets;

    if not found then
        return jsonb_build_object('ok', false, 'error', 'USER_NOT_FOUND');
    end if;

    v_new_balance := coalesce(v_points.total_points, 0) - v_cost;

    update public.points
    set spent_points = coalesce(spent_points, 0) + v_cost,
        total_points = v_new_balance,
        updated_at = now()
    where user_id = p_user_id;

    insert into public.points_transactions (
        user_id, amount, transaction_type, reference_type,
        idempotency_key, metadata
    ) values (
        p_user_id, -v_cost, 'ticket_purchase', 'tickets',
        p_idempotency_key,
        jsonb_build_object(
            'amount', p_amount,
            'unit_cost', p_unit_cost,
            'new_balance', v_new_balance,
            'tickets', v_new_tickets
        )
    );

    return jsonb_build_object(
        'ok', true,
        'new_balance', v_new_balance,
        'tickets', v_new_tickets
    );
end;
$$;

create or replace function public.purchase_store_lot(
    p_user_id bigint,
    p_lot_id bigint,
    p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_lot public.store_lots%rowtype;
    v_points public.points%rowtype;
    v_existing public.store_purchases%rowtype;
    v_purchase_id bigint;
    v_user_bought integer;
    v_new_sold integer;
    v_new_balance integer;
    v_purchase_status text := 'paid';
    v_ticket_reward integer := 0;
begin
    select * into v_existing
    from public.store_purchases
    where idempotency_key = p_idempotency_key;

    if found then
        return jsonb_build_object(
            'ok', true,
            'duplicate', true,
            'purchase_id', v_existing.id,
            'status', v_existing.status
        );
    end if;

    select * into v_lot
    from public.store_lots
    where id = p_lot_id
    for update;

    if not found then
        return jsonb_build_object('ok', false, 'error', 'LOT_NOT_FOUND');
    end if;

    if v_lot.status <> 'active' then
        return jsonb_build_object('ok', false, 'error', 'LOT_NOT_ACTIVE');
    end if;

    if v_lot.sold_quantity >= v_lot.total_quantity then
        return jsonb_build_object('ok', false, 'error', 'SOLD_OUT');
    end if;

    select count(*)::integer into v_user_bought
    from public.store_purchases
    where lot_id = p_lot_id
      and user_id = p_user_id
      and status in ('paid', 'fulfilled');

    if v_user_bought >= v_lot.per_user_limit then
        return jsonb_build_object('ok', false, 'error', 'USER_LIMIT_REACHED');
    end if;

    select * into v_points
    from public.points
    where user_id = p_user_id
    for update;

    if not found then
        return jsonb_build_object('ok', false, 'error', 'POINTS_NOT_FOUND');
    end if;

    if coalesce(v_points.total_points, 0) < v_lot.price_rp then
        return jsonb_build_object('ok', false, 'error', 'INSUFFICIENT_POINTS');
    end if;

    if v_lot.reward_type = 'ticket' then
        begin
            v_ticket_reward := greatest(0, coalesce((v_lot.reward_payload->>'tickets')::integer, 0));
        exception when invalid_text_representation then
            v_ticket_reward := 0;
        end;
        if v_ticket_reward > 0 then
            update public.users
            set active_tickets = coalesce(active_tickets, 0) + v_ticket_reward
            where telegram_id = p_user_id;
            v_purchase_status := 'fulfilled';
        end if;
    end if;

    v_new_balance := coalesce(v_points.total_points, 0) - v_lot.price_rp;

    update public.points
    set spent_points = coalesce(spent_points, 0) + v_lot.price_rp,
        total_points = v_new_balance,
        updated_at = now()
    where user_id = p_user_id;

    v_new_sold := v_lot.sold_quantity + 1;
    update public.store_lots
    set sold_quantity = v_new_sold,
        status = case when v_new_sold >= total_quantity then 'sold_out' else status end
    where id = p_lot_id;

    insert into public.store_purchases (
        lot_id, user_id, price_rp, quantity, status,
        idempotency_key, fulfilled_at
    ) values (
        p_lot_id, p_user_id, v_lot.price_rp, 1, v_purchase_status,
        p_idempotency_key,
        case when v_purchase_status = 'fulfilled' then now() else null end
    ) returning id into v_purchase_id;

    insert into public.points_transactions (
        user_id, amount, transaction_type, reference_type,
        reference_id, idempotency_key, metadata
    ) values (
        p_user_id, -v_lot.price_rp, 'store_purchase', 'store_purchase',
        v_purchase_id, 'lot:' || p_idempotency_key,
        jsonb_build_object(
            'lot_id', p_lot_id,
            'lot_title', v_lot.title,
            'new_balance', v_new_balance,
            'remaining', v_lot.total_quantity - v_new_sold
        )
    );

    return jsonb_build_object(
        'ok', true,
        'purchase_id', v_purchase_id,
        'status', v_purchase_status,
        'new_balance', v_new_balance,
        'remaining', v_lot.total_quantity - v_new_sold,
        'ticket_reward', v_ticket_reward
    );
end;
$$;

create or replace function public.join_giveaway_atomic(
    p_giveaway_id bigint,
    p_user_id bigint,
    p_username text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_status text;
    v_active_tickets integer;
    v_tickets_used integer;
    v_participant_id bigint;
begin
    select status into v_status
    from public.giveaways
    where id = p_giveaway_id
    for share;

    if not found then
        return jsonb_build_object('ok', false, 'error', 'GIVEAWAY_NOT_FOUND');
    end if;

    if v_status <> 'active' then
        return jsonb_build_object('ok', false, 'error', 'GIVEAWAY_NOT_ACTIVE');
    end if;

    select coalesce(active_tickets, 0) into v_active_tickets
    from public.users
    where telegram_id = p_user_id
    for update;

    if not found then
        return jsonb_build_object('ok', false, 'error', 'USER_NOT_FOUND');
    end if;

    v_tickets_used := greatest(1, v_active_tickets);

    insert into public.participants (
        giveaway_id, user_id, username, tickets_used
    ) values (
        p_giveaway_id, p_user_id, p_username, v_tickets_used
    )
    on conflict (giveaway_id, user_id) do nothing
    returning id into v_participant_id;

    if v_participant_id is null then
        return jsonb_build_object('ok', false, 'error', 'ALREADY_JOINED');
    end if;

    if v_active_tickets > 0 then
        update public.users
        set active_tickets = 0
        where telegram_id = p_user_id;
    end if;

    return jsonb_build_object(
        'ok', true,
        'participant_id', v_participant_id,
        'tickets_used', v_tickets_used,
        'bonus_tickets_consumed', v_active_tickets
    );
end;
$$;

create or replace function public.claim_giveaway_completion(p_giveaway_id bigint)
returns boolean
language sql
security definer
set search_path = public, pg_temp
as $$
    update public.giveaways
    set status = 'processing', updated_at = now()
    where id = p_giveaway_id and status = 'active'
    returning true;
$$;

alter table public.store_lots enable row level security;
alter table public.store_purchases enable row level security;
alter table public.points_transactions enable row level security;

revoke all on public.store_lots, public.store_purchases, public.points_transactions
from anon, authenticated;
grant all on public.store_lots, public.store_purchases, public.points_transactions
to service_role;
grant usage, select on all sequences in schema public to service_role;

revoke all on function public.purchase_store_tickets(bigint, integer, integer, text)
from public, anon, authenticated;
revoke all on function public.purchase_store_lot(bigint, bigint, text)
from public, anon, authenticated;
revoke all on function public.join_giveaway_atomic(bigint, bigint, text)
from public, anon, authenticated;
revoke all on function public.claim_giveaway_completion(bigint)
from public, anon, authenticated;

grant execute on function public.purchase_store_tickets(bigint, integer, integer, text) to service_role;
grant execute on function public.purchase_store_lot(bigint, bigint, text) to service_role;
grant execute on function public.join_giveaway_atomic(bigint, bigint, text) to service_role;
grant execute on function public.claim_giveaway_completion(bigint) to service_role;

commit;
