begin;

alter table public.points
    add column if not exists external_points integer not null default 0;

create table if not exists public.ticket_offers (
    code text primary key,
    ticket_count integer not null check (ticket_count between 1 and 10),
    price_rp integer not null check (price_rp > 0),
    mode text not null default 'add' check (mode in ('add', 'fill')),
    pricing_mode text not null default 'fixed'
        check (pricing_mode in ('fixed', 'per_ticket')),
    sort_order integer not null default 0,
    active boolean not null default true,
    updated_at timestamptz not null default now()
);

insert into public.ticket_offers
    (code, ticket_count, price_rp, mode, pricing_mode, sort_order)
values
    ('1', 1, 50, 'add', 'fixed', 10),
    ('5', 5, 225, 'add', 'fixed', 20),
    ('max', 10, 50, 'add', 'per_ticket', 30)
on conflict (code) do nothing;

create table if not exists public.giveaway_ticket_balances (
    giveaway_id bigint not null references public.giveaways(id) on delete cascade,
    user_id bigint not null references public.users(telegram_id) on delete cascade,
    tickets integer not null default 1 check (tickets >= 1),
    purchased_rp integer not null default 0 check (purchased_rp >= 0),
    consumed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (giveaway_id, user_id)
);

create index if not exists idx_giveaway_ticket_balances_user
    on public.giveaway_ticket_balances(user_id, giveaway_id);

create or replace function public.consume_finished_giveaway_tickets()
returns trigger language plpgsql set search_path = public, pg_temp as $$
begin
    if old.status = 'active' and new.status <> 'active' then
        update public.giveaway_ticket_balances
        set tickets = 1, consumed_at = coalesce(consumed_at, now()), updated_at = now()
        where giveaway_id = new.id and consumed_at is null;
    end if;
    return new;
end;
$$;
drop trigger if exists trg_consume_finished_giveaway_tickets on public.giveaways;
create trigger trg_consume_finished_giveaway_tickets
after update of status on public.giveaways
for each row execute function public.consume_finished_giveaway_tickets();

create table if not exists public.gram_deposits (
    id bigint generated by default as identity primary key,
    event_id text not null,
    action_index integer not null default 0,
    user_id bigint references public.users(telegram_id) on delete set null,
    telegram_username text,
    sender_address text,
    amount_gram numeric(30, 9) not null check (amount_gram > 0),
    rp_amount integer not null check (rp_amount > 0),
    status text not null default 'credited'
        check (status in ('credited', 'rejected')),
    raw_data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (event_id, action_index)
);

create index if not exists idx_gram_deposits_user
    on public.gram_deposits(user_id, created_at desc);

create table if not exists public.otc_listings (
    id bigint generated by default as identity primary key,
    seller_id bigint not null references public.users(telegram_id) on delete cascade,
    trade_type text not null check (trade_type in ('WTS', 'WTB')),
    item_name text not null check (length(trim(item_name)) between 1 and 500),
    item_url text,
    price_text text,
    chat_id bigint,
    message_id bigint,
    status text not null default 'active'
        check (status in ('draft', 'active', 'closed', 'sold', 'deleted')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_otc_listings_active
    on public.otc_listings(status, created_at desc);

create table if not exists public.otc_offers (
    id bigint generated by default as identity primary key,
    listing_id bigint not null references public.otc_listings(id) on delete cascade,
    buyer_id bigint not null references public.users(telegram_id) on delete cascade,
    seller_id bigint not null references public.users(telegram_id) on delete cascade,
    amount_ton numeric(30, 9) not null check (amount_ton > 0),
    status text not null default 'pending'
        check (status in ('pending', 'accepted', 'declined', 'cancelled')),
    created_at timestamptz not null default now(),
    responded_at timestamptz
);

create index if not exists idx_otc_offers_seller_pending
    on public.otc_offers(seller_id, status, created_at desc);
create index if not exists idx_otc_offers_buyer
    on public.otc_offers(buyer_id, created_at desc);

create or replace function public.purchase_giveaway_tickets(
    p_user_id bigint,
    p_giveaway_id bigint,
    p_offer_code text,
    p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_status text;
    v_offer public.ticket_offers%rowtype;
    v_points public.points%rowtype;
    v_existing public.points_transactions%rowtype;
    v_current integer;
    v_legacy integer;
    v_add integer;
    v_cost integer;
    v_new integer;
    v_new_balance integer;
begin
    perform pg_advisory_xact_lock(hashtextextended(p_idempotency_key, 0));

    select * into v_existing from public.points_transactions
    where idempotency_key = p_idempotency_key;
    if found then
        return jsonb_build_object(
            'ok', true, 'duplicate', true,
            'tickets', coalesce((v_existing.metadata->>'tickets')::integer, 1),
            'cost', abs(v_existing.amount),
            'new_balance', coalesce((v_existing.metadata->>'new_balance')::integer, 0)
        );
    end if;

    select status into v_status from public.giveaways
    where id = p_giveaway_id for share;
    if not found then
        return jsonb_build_object('ok', false, 'error', 'GIVEAWAY_NOT_FOUND');
    end if;
    if v_status <> 'active' then
        return jsonb_build_object('ok', false, 'error', 'GIVEAWAY_NOT_ACTIVE');
    end if;

    select * into v_offer from public.ticket_offers
    where code = p_offer_code and active = true;
    if not found then
        return jsonb_build_object('ok', false, 'error', 'OFFER_NOT_FOUND');
    end if;

    select coalesce(active_tickets, 0) into v_legacy
    from public.users where telegram_id = p_user_id for update;
    if not found then
        return jsonb_build_object('ok', false, 'error', 'USER_NOT_FOUND');
    end if;

    insert into public.giveaway_ticket_balances (giveaway_id, user_id, tickets)
    values (p_giveaway_id, p_user_id, greatest(1, v_legacy))
    on conflict (giveaway_id, user_id) do nothing;

    select tickets into v_current from public.giveaway_ticket_balances
    where giveaway_id = p_giveaway_id and user_id = p_user_id for update;

    v_add := v_offer.ticket_count;
    if v_add <= 0 then
        return jsonb_build_object('ok', false, 'error', 'TICKET_LIMIT_REACHED');
    end if;

    v_cost := case
        when v_offer.pricing_mode = 'per_ticket' then v_offer.price_rp * v_add
        else v_offer.price_rp
    end;

    select * into v_points from public.points
    where user_id = p_user_id for update;
    if not found then
        return jsonb_build_object('ok', false, 'error', 'POINTS_NOT_FOUND');
    end if;
    if coalesce(v_points.total_points, 0) < v_cost then
        return jsonb_build_object('ok', false, 'error', 'INSUFFICIENT_POINTS');
    end if;

    v_new := v_current + v_add;
    v_new_balance := coalesce(v_points.total_points, 0) - v_cost;

    update public.giveaway_ticket_balances
    set tickets = v_new,
        purchased_rp = purchased_rp + v_cost,
        consumed_at = null,
        updated_at = now()
    where giveaway_id = p_giveaway_id and user_id = p_user_id;

    update public.participants
    set tickets_used = v_new
    where giveaway_id = p_giveaway_id and user_id = p_user_id;

    update public.users set active_tickets = 0 where telegram_id = p_user_id;
    update public.points
    set spent_points = coalesce(spent_points, 0) + v_cost,
        total_points = v_new_balance,
        updated_at = now()
    where user_id = p_user_id;

    insert into public.points_transactions (
        user_id, amount, transaction_type, reference_type,
        reference_id, idempotency_key, metadata
    ) values (
        p_user_id, -v_cost, 'giveaway_ticket_purchase', 'giveaway',
        p_giveaway_id, p_idempotency_key,
        jsonb_build_object(
            'offer_code', p_offer_code, 'added', v_add,
            'tickets', v_new, 'new_balance', v_new_balance
        )
    );

    return jsonb_build_object(
        'ok', true, 'tickets', v_new, 'added', v_add,
        'cost', v_cost, 'new_balance', v_new_balance
    );
end;
$$;

create or replace function public.join_giveaway_atomic(
    p_giveaway_id bigint,
    p_user_id bigint,
    p_username text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_status text;
    v_legacy integer;
    v_tickets integer;
    v_participant_id bigint;
begin
    select status into v_status from public.giveaways
    where id = p_giveaway_id for share;
    if not found then
        return jsonb_build_object('ok', false, 'error', 'GIVEAWAY_NOT_FOUND');
    end if;
    if v_status <> 'active' then
        return jsonb_build_object('ok', false, 'error', 'GIVEAWAY_NOT_ACTIVE');
    end if;

    select coalesce(active_tickets, 0) into v_legacy from public.users
    where telegram_id = p_user_id for update;
    if not found then
        return jsonb_build_object('ok', false, 'error', 'USER_NOT_FOUND');
    end if;

    insert into public.giveaway_ticket_balances (giveaway_id, user_id, tickets)
    values (p_giveaway_id, p_user_id, greatest(1, v_legacy))
    on conflict (giveaway_id, user_id) do nothing;

    select tickets into v_tickets from public.giveaway_ticket_balances
    where giveaway_id = p_giveaway_id and user_id = p_user_id for update;

    insert into public.participants (giveaway_id, user_id, username, tickets_used)
    values (p_giveaway_id, p_user_id, p_username, v_tickets)
    on conflict (giveaway_id, user_id) do nothing
    returning id into v_participant_id;
    if v_participant_id is null then
        return jsonb_build_object('ok', false, 'error', 'ALREADY_JOINED');
    end if;

    update public.giveaway_ticket_balances set consumed_at = null, updated_at = now()
    where giveaway_id = p_giveaway_id and user_id = p_user_id;
    update public.users set active_tickets = 0 where telegram_id = p_user_id;

    return jsonb_build_object(
        'ok', true, 'participant_id', v_participant_id,
        'tickets_used', v_tickets, 'bonus_tickets_consumed', greatest(0, v_tickets - 1)
    );
end;
$$;

create or replace function public.claim_gram_deposit(
    p_event_id text,
    p_action_index integer,
    p_username text,
    p_sender_address text,
    p_amount_gram numeric,
    p_rp_amount integer,
    p_raw_data jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_user_id bigint;
    v_new_balance integer;
    v_key text := 'gram:' || p_event_id || ':' || p_action_index::text;
begin
    perform pg_advisory_xact_lock(hashtextextended(v_key, 0));
    if exists (
        select 1 from public.gram_deposits
        where event_id = p_event_id and action_index = p_action_index
    ) then
        return jsonb_build_object('ok', true, 'duplicate', true);
    end if;
    if p_amount_gram < 0.1 or p_rp_amount <= 0 or nullif(trim(p_username), '') is null then
        return jsonb_build_object('ok', false, 'error', 'INVALID_DEPOSIT');
    end if;

    select telegram_id into v_user_id from public.users
    where lower(username) = lower(trim(leading '@' from trim(p_username)))
    order by telegram_id limit 1;
    if not found then
        return jsonb_build_object('ok', false, 'error', 'USER_NOT_FOUND');
    end if;

    insert into public.points (user_id, external_points, total_points)
    values (v_user_id, p_rp_amount, p_rp_amount)
    on conflict (user_id) do update
    set external_points = coalesce(public.points.external_points, 0) + p_rp_amount,
        total_points = coalesce(public.points.total_points, 0) + p_rp_amount,
        updated_at = now()
    returning total_points into v_new_balance;

    insert into public.gram_deposits (
        event_id, action_index, user_id, telegram_username,
        sender_address, amount_gram, rp_amount, raw_data
    ) values (
        p_event_id, p_action_index, v_user_id, p_username,
        p_sender_address, p_amount_gram, p_rp_amount, p_raw_data
    );

    insert into public.points_transactions (
        user_id, amount, transaction_type, reference_type,
        idempotency_key, metadata
    ) values (
        v_user_id, p_rp_amount, 'gram_deposit', 'gram', v_key,
        jsonb_build_object(
            'event_id', p_event_id, 'amount_gram', p_amount_gram,
            'new_balance', v_new_balance
        )
    );

    return jsonb_build_object(
        'ok', true, 'user_id', v_user_id,
        'rp_amount', p_rp_amount, 'new_balance', v_new_balance
    );
end;
$$;

create or replace function public.respond_otc_offer(
    p_offer_id bigint,
    p_seller_id bigint,
    p_status text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_offer public.otc_offers%rowtype;
begin
    if p_status not in ('accepted', 'declined') then
        return jsonb_build_object('ok', false, 'error', 'INVALID_STATUS');
    end if;
    update public.otc_offers
    set status = p_status, responded_at = now()
    where id = p_offer_id and seller_id = p_seller_id and status = 'pending'
    returning * into v_offer;
    if not found then
        return jsonb_build_object('ok', false, 'error', 'OFFER_UNAVAILABLE');
    end if;
    return jsonb_build_object(
        'ok', true, 'offer_id', v_offer.id, 'status', v_offer.status,
        'buyer_id', v_offer.buyer_id, 'seller_id', v_offer.seller_id,
        'listing_id', v_offer.listing_id, 'amount_ton', v_offer.amount_ton
    );
end;
$$;

alter table public.ticket_offers enable row level security;
alter table public.giveaway_ticket_balances enable row level security;
alter table public.gram_deposits enable row level security;
alter table public.otc_listings enable row level security;
alter table public.otc_offers enable row level security;

revoke all on public.ticket_offers, public.giveaway_ticket_balances,
    public.gram_deposits, public.otc_listings, public.otc_offers
from anon, authenticated;
grant all on public.ticket_offers, public.giveaway_ticket_balances,
    public.gram_deposits, public.otc_listings, public.otc_offers
to service_role;
grant usage, select on all sequences in schema public to service_role;

revoke all on function public.purchase_giveaway_tickets(bigint, bigint, text, text)
from public, anon, authenticated;
revoke all on function public.claim_gram_deposit(text, integer, text, text, numeric, integer, jsonb)
from public, anon, authenticated;
revoke all on function public.respond_otc_offer(bigint, bigint, text)
from public, anon, authenticated;

grant execute on function public.purchase_giveaway_tickets(bigint, bigint, text, text)
to service_role;
grant execute on function public.claim_gram_deposit(text, integer, text, text, numeric, integer, jsonb)
to service_role;
grant execute on function public.respond_otc_offer(bigint, bigint, text)
to service_role;

insert into public.settings (key, value) values
    ('ticket_offers_version', 'v2'),
    ('boost_nft_purchase_rp', '0'),
    ('boost_sticker_purchase_rp', '0'),
    ('gram_rp_per_gram', '10')
on conflict (key) do nothing;

commit;
